app:
  name: "pricing-service"
  host: "127.0.0.1"
  port: 8084
  env: "development"

redis:
  host: "localhost"
  port: 6379

logger:
  level: "info"
  filepath: "logs/app.log"

consul:
  address: "localhost:8500"
  wait_time: "15s"