app:
  name: "pricing-service"
  host: "pricing-service"
  port: 8084
  env: "production"

redis:
  host: "redis"
  port: 6379

logger:
  level: "info"
  filepath: "logs/app.log"

consul:
  address: "consul:8500"
  wait_time: "15s"