[http]
    [http.routers]
        [http.routers.account-service]
            entryPoints = ["http"]
            rule = "Host(`localhost`) && PathPrefix(`/api/v1/accounts`)"
            service = "account-service"

    [http.services]
        [http.services.account-service]
            [http.services.account-service.loadBalancer]
                [[http.services.account-svc.loadBalancer.servers]]
                    url = "http://user-service:8081"
