services:
  postgres:
    image: postgres:18.3
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: witrack_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - witrack_backend_net

volumes:
  postgres_data:

networks:
  witrack_backend_net:
    driver: bridge