services:
  postgres:
    image: postgres:17.6
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: witrack_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - witrack_backend_net

volumes:
  pg_data:

networks:
  witrack_backend_net:
    driver: bridge