server:
  port: 8081
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:mem:payment}
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

  kafka:
    bootstrap-servers: localhost:9092, localhost:9094, localhost:9096
    consumer:
      group-id: payment-consumer-group
      auto-offset-reset: earliest
    listener:
      concurrency: 3
      ack-mode: record
      batch-listener: false
    topic:
      order:
        events: "example.order.events"

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
springdoc:
  pathsToMatch: /api/**
