server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: backend-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:secret@localhost:27017/witickets?authSource=admin}
      uuid-representation: standard
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,threaddump
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:YXV0aGVudGljYXRlVGhpczM2Qnl0ZXNLZXkYXV0aGVudGljYXRlVGhpczM2Qnl0ZXNLZXk}
  #  1 day
  expiry: ${JWT_EXPIRY_IN:86400000}

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      UserEmailUnique: USER_EMAIL_UNIQUE
      TicketCodeUnique: TICKET_CODE_UNIQUE

springdoc:
  paths-to-match: /api/**

clients:
  cors:
    allowed-origins: ${CLIENTS_ALLOWED:http://localhost:8080,https://example.com}