// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/couponPolicies": {
            "get": {
                "description": "Get coupon policies by ID, code, or name. If no parameters are provided, return all coupon policies.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coupon Policy"
                ],
                "summary": "Search coupon policies (by ID, Code, Name, or all)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Coupon Policy ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Coupon Code",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Coupon Name",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/coupon.CouponPolicy"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/couponPolicies/dummy": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coupon Policy"
                ],
                "summary": "Create dummy coupon policies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/coupon.CouponPolicy"
                            }
                        }
                    }
                }
            }
        },
        "/coupons": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coupons"
                ],
                "summary": "List coupons",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "coupon.Coupon": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "couponPolicy": {
                    "$ref": "#/definitions/coupon.CouponPolicy"
                },
                "couponPolicyId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "orderId": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/coupon.CouponStatus"
                },
                "updatedAt": {
                    "type": "string"
                },
                "usedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "coupon.CouponPolicy": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "coupons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/coupon.Coupon"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "discountType": {
                    "$ref": "#/definitions/coupon.DiscountType"
                },
                "discountValue": {
                    "type": "integer"
                },
                "endTime": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "maximumDiscountAmount": {
                    "type": "integer"
                },
                "minimumOrderAmount": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "totalQuantity": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "coupon.CouponStatus": {
            "type": "string",
            "enum": [
                "AVAILABLE",
                "USED",
                "EXPIRED",
                "CANCELED"
            ],
            "x-enum-varnames": [
                "CouponStatusAvailable",
                "CouponStatusUsed",
                "CouponStatusExpired",
                "CouponStatusCanceled"
            ]
        },
        "coupon.DiscountType": {
            "type": "string",
            "enum": [
                "FIXED_AMOUNT",
                "PERCENTAGE"
            ],
            "x-enum-varnames": [
                "DiscountTypeFixedAmount",
                "DiscountTypePercentage"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Coupon API V1",
	Description:      "Coupon API V1",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register("couponSwaggerV1", SwaggerInfo)
}
