{
 "title": "Logging Promotions Apps",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "API Gateway Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"api-gateway\"}"
    }
   ]
  },
  {
   "title": "Service Registry Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"service-registry\"}"
    }
   ]
  },
  {
   "title": "User Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"user-service\"}"
    }
   ]
  },
  {
   "title": "Coupon Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"coupon-service\"}"
    }
   ]
  },
  {
   "title": "Point Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"point-service\"}"
    }
   ]
  },
  {
   "title": "Timesale Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"timesale-service\"}"
    }
   ]
  }
 ]
}