basePath: /api/v1/pricings
definitions:
  pricing.Pricing:
    properties:
      discount:
        description: Discount percentage (e.g., 0.10 for 10%)
        type: number
      final_price:
        description: Final price = (base_price * (1 + markup)) - discount
        type: number
      markup:
        description: Markup percentage (e.g., 0.15 for 15%)
        type: number
      product_id:
        description: ID of the product
        type: string
    type: object
  pricing.PricingRuleRequest:
    properties:
      default_discount:
        maximum: 1
        minimum: 0
        type: number
      default_markup:
        maximum: 1
        minimum: 0
        type: number
      discount_reduction:
        maximum: 1
        minimum: 0
        type: number
      markup_increase:
        maximum: 1
        minimum: 0
        type: number
      product_id:
        type: string
      stock_threshold:
        minimum: 0
        type: integer
    required:
    - product_id
    type: object
host: localhost:8084
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: This is an pricing service API.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: Pricing Service API
  version: "1.0"
paths:
  /{id}:
    get:
      consumes:
      - application/json
      description: Retrieve pricing rule and calculate final price based on current
        stock level
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Calculated pricing result
          schema:
            $ref: '#/definitions/pricing.Pricing'
        "400":
          description: Invalid request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get calculated pricing for a product
      tags:
      - pricing
  /rules:
    post:
      consumes:
      - application/json
      description: Set pricing rule including markup, discount, and thresholds for
        a specific product
      parameters:
      - description: Pricing Rule Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/pricing.PricingRuleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created pricing rule
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Validation or binding error
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Create or update pricing rule for a product
      tags:
      - pricing
swagger: "2.0"
