server:
  name: coupon-service
  port: 8081
  environment: production
  log_level: info
  log_filepath: logs/app.log

postgres:
  host: localhost
  port: 5432
  user: demo_user
  password: demo_pass
  database: coupon_db
  sslmode: disable
  time_zone: Asia/Jakarta
  max_conns: 10
  max_idle_conns: 5
  max_lifetime: 1h
  log_level: warn