// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: api/membership/membership.proto

package membership

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Fullname      string                 `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMembershipRequest) Reset() {
	*x = CreateMembershipRequest{}
	mi := &file_api_membership_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMembershipRequest) ProtoMessage() {}

func (x *CreateMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_membership_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMembershipRequest.ProtoReflect.Descriptor instead.
func (*CreateMembershipRequest) Descriptor() ([]byte, []int) {
	return file_api_membership_membership_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMembershipRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateMembershipRequest) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *CreateMembershipRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateMembershipReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMembershipReply) Reset() {
	*x = CreateMembershipReply{}
	mi := &file_api_membership_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMembershipReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMembershipReply) ProtoMessage() {}

func (x *CreateMembershipReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_membership_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMembershipReply.ProtoReflect.Descriptor instead.
func (*CreateMembershipReply) Descriptor() ([]byte, []int) {
	return file_api_membership_membership_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMembershipReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateMembershipReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UpdateMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Fullname      string                 `protobuf:"bytes,3,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMembershipRequest) Reset() {
	*x = UpdateMembershipRequest{}
	mi := &file_api_membership_membership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMembershipRequest) ProtoMessage() {}

func (x *UpdateMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_membership_membership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMembershipRequest.ProtoReflect.Descriptor instead.
func (*UpdateMembershipRequest) Descriptor() ([]byte, []int) {
	return file_api_membership_membership_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMembershipRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMembershipRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateMembershipRequest) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *UpdateMembershipRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UpdateMembershipReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMembershipReply) Reset() {
	*x = UpdateMembershipReply{}
	mi := &file_api_membership_membership_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMembershipReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMembershipReply) ProtoMessage() {}

func (x *UpdateMembershipReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_membership_membership_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMembershipReply.ProtoReflect.Descriptor instead.
func (*UpdateMembershipReply) Descriptor() ([]byte, []int) {
	return file_api_membership_membership_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMembershipReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateMembershipReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type DeleteMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMembershipRequest) Reset() {
	*x = DeleteMembershipRequest{}
	mi := &file_api_membership_membership_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMembershipRequest) ProtoMessage() {}

func (x *DeleteMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_membership_membership_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMembershipRequest.ProtoReflect.Descriptor instead.
func (*DeleteMembershipRequest) Descriptor() ([]byte, []int) {
	return file_api_membership_membership_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteMembershipRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMembershipReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMembershipReply) Reset() {
	*x = DeleteMembershipReply{}
	mi := &file_api_membership_membership_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMembershipReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMembershipReply) ProtoMessage() {}

func (x *DeleteMembershipReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_membership_membership_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMembershipReply.ProtoReflect.Descriptor instead.
func (*DeleteMembershipReply) Descriptor() ([]byte, []int) {
	return file_api_membership_membership_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMembershipReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembershipRequest) Reset() {
	*x = GetMembershipRequest{}
	mi := &file_api_membership_membership_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipRequest) ProtoMessage() {}

func (x *GetMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_membership_membership_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipRequest.ProtoReflect.Descriptor instead.
func (*GetMembershipRequest) Descriptor() ([]byte, []int) {
	return file_api_membership_membership_proto_rawDescGZIP(), []int{6}
}

func (x *GetMembershipRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMembershipReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Fullname      string                 `protobuf:"bytes,3,opt,name=fullname,proto3" json:"fullname,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembershipReply) Reset() {
	*x = GetMembershipReply{}
	mi := &file_api_membership_membership_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembershipReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipReply) ProtoMessage() {}

func (x *GetMembershipReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_membership_membership_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipReply.ProtoReflect.Descriptor instead.
func (*GetMembershipReply) Descriptor() ([]byte, []int) {
	return file_api_membership_membership_proto_rawDescGZIP(), []int{7}
}

func (x *GetMembershipReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMembershipReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetMembershipReply) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *GetMembershipReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetMembershipReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembershipRequest) Reset() {
	*x = ListMembershipRequest{}
	mi := &file_api_membership_membership_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembershipRequest) ProtoMessage() {}

func (x *ListMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_membership_membership_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembershipRequest.ProtoReflect.Descriptor instead.
func (*ListMembershipRequest) Descriptor() ([]byte, []int) {
	return file_api_membership_membership_proto_rawDescGZIP(), []int{8}
}

func (x *ListMembershipRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMembershipRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMembershipReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memberships   []*GetMembershipReply  `protobuf:"bytes,1,rep,name=memberships,proto3" json:"memberships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembershipReply) Reset() {
	*x = ListMembershipReply{}
	mi := &file_api_membership_membership_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembershipReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembershipReply) ProtoMessage() {}

func (x *ListMembershipReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_membership_membership_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembershipReply.ProtoReflect.Descriptor instead.
func (*ListMembershipReply) Descriptor() ([]byte, []int) {
	return file_api_membership_membership_proto_rawDescGZIP(), []int{9}
}

func (x *ListMembershipReply) GetMemberships() []*GetMembershipReply {
	if x != nil {
		return x.Memberships
	}
	return nil
}

var File_api_membership_membership_proto protoreflect.FileDescriptor

const file_api_membership_membership_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/membership/membership.proto\x12\x0eapi.membership\"g\n" +
	"\x17CreateMembershipRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bfullname\x18\x02 \x01(\tR\bfullname\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"F\n" +
	"\x15CreateMembershipReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\"w\n" +
	"\x17UpdateMembershipRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bfullname\x18\x03 \x01(\tR\bfullname\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"P\n" +
	"\x15UpdateMembershipReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\tR\tupdatedAt\")\n" +
	"\x17DeleteMembershipRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteMembershipReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"&\n" +
	"\x14GetMembershipRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x94\x01\n" +
	"\x12GetMembershipReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bfullname\x18\x03 \x01(\tR\bfullname\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"H\n" +
	"\x15ListMembershipRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"[\n" +
	"\x13ListMembershipReply\x12D\n" +
	"\vmemberships\x18\x01 \x03(\v2\".api.membership.GetMembershipReplyR\vmemberships2\xf1\x03\n" +
	"\n" +
	"Membership\x12b\n" +
	"\x10CreateMembership\x12'.api.membership.CreateMembershipRequest\x1a%.api.membership.CreateMembershipReply\x12b\n" +
	"\x10UpdateMembership\x12'.api.membership.UpdateMembershipRequest\x1a%.api.membership.UpdateMembershipReply\x12b\n" +
	"\x10DeleteMembership\x12'.api.membership.DeleteMembershipRequest\x1a%.api.membership.DeleteMembershipReply\x12Y\n" +
	"\rGetMembership\x12$.api.membership.GetMembershipRequest\x1a\".api.membership.GetMembershipReply\x12\\\n" +
	"\x0eListMembership\x12%.api.membership.ListMembershipRequest\x1a#.api.membership.ListMembershipReplyB8\n" +
	"\x0eapi.membershipP\x01Z$membership/api/membership;membershipb\x06proto3"

var (
	file_api_membership_membership_proto_rawDescOnce sync.Once
	file_api_membership_membership_proto_rawDescData []byte
)

func file_api_membership_membership_proto_rawDescGZIP() []byte {
	file_api_membership_membership_proto_rawDescOnce.Do(func() {
		file_api_membership_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_membership_membership_proto_rawDesc), len(file_api_membership_membership_proto_rawDesc)))
	})
	return file_api_membership_membership_proto_rawDescData
}

var file_api_membership_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_membership_membership_proto_goTypes = []any{
	(*CreateMembershipRequest)(nil), // 0: api.membership.CreateMembershipRequest
	(*CreateMembershipReply)(nil),   // 1: api.membership.CreateMembershipReply
	(*UpdateMembershipRequest)(nil), // 2: api.membership.UpdateMembershipRequest
	(*UpdateMembershipReply)(nil),   // 3: api.membership.UpdateMembershipReply
	(*DeleteMembershipRequest)(nil), // 4: api.membership.DeleteMembershipRequest
	(*DeleteMembershipReply)(nil),   // 5: api.membership.DeleteMembershipReply
	(*GetMembershipRequest)(nil),    // 6: api.membership.GetMembershipRequest
	(*GetMembershipReply)(nil),      // 7: api.membership.GetMembershipReply
	(*ListMembershipRequest)(nil),   // 8: api.membership.ListMembershipRequest
	(*ListMembershipReply)(nil),     // 9: api.membership.ListMembershipReply
}
var file_api_membership_membership_proto_depIdxs = []int32{
	7, // 0: api.membership.ListMembershipReply.memberships:type_name -> api.membership.GetMembershipReply
	0, // 1: api.membership.Membership.CreateMembership:input_type -> api.membership.CreateMembershipRequest
	2, // 2: api.membership.Membership.UpdateMembership:input_type -> api.membership.UpdateMembershipRequest
	4, // 3: api.membership.Membership.DeleteMembership:input_type -> api.membership.DeleteMembershipRequest
	6, // 4: api.membership.Membership.GetMembership:input_type -> api.membership.GetMembershipRequest
	8, // 5: api.membership.Membership.ListMembership:input_type -> api.membership.ListMembershipRequest
	1, // 6: api.membership.Membership.CreateMembership:output_type -> api.membership.CreateMembershipReply
	3, // 7: api.membership.Membership.UpdateMembership:output_type -> api.membership.UpdateMembershipReply
	5, // 8: api.membership.Membership.DeleteMembership:output_type -> api.membership.DeleteMembershipReply
	7, // 9: api.membership.Membership.GetMembership:output_type -> api.membership.GetMembershipReply
	9, // 10: api.membership.Membership.ListMembership:output_type -> api.membership.ListMembershipReply
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_membership_membership_proto_init() }
func file_api_membership_membership_proto_init() {
	if File_api_membership_membership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_membership_membership_proto_rawDesc), len(file_api_membership_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_membership_membership_proto_goTypes,
		DependencyIndexes: file_api_membership_membership_proto_depIdxs,
		MessageInfos:      file_api_membership_membership_proto_msgTypes,
	}.Build()
	File_api_membership_membership_proto = out.File
	file_api_membership_membership_proto_goTypes = nil
	file_api_membership_membership_proto_depIdxs = nil
}
