// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user_test

import (
	"context"

	"example.com/api/users/internal/user"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIService creates a new instance of MockIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIService {
	mock := &MockIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIService is an autogenerated mock type for the IService type
type MockIService struct {
	mock.Mock
}

type MockIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIService) EXPECT() *MockIService_Expecter {
	return &MockIService_Expecter{mock: &_m.Mock}
}

// SignIn provides a mock function for the type MockIService
func (_mock *MockIService) SignIn(ctx context.Context, param user.SignInParam) (user.UserWithTokenResponse, error) {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for SignIn")
	}

	var r0 user.UserWithTokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.SignInParam) (user.UserWithTokenResponse, error)); ok {
		return returnFunc(ctx, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.SignInParam) user.UserWithTokenResponse); ok {
		r0 = returnFunc(ctx, param)
	} else {
		r0 = ret.Get(0).(user.UserWithTokenResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.SignInParam) error); ok {
		r1 = returnFunc(ctx, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_SignIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignIn'
type MockIService_SignIn_Call struct {
	*mock.Call
}

// SignIn is a helper method to define mock.On call
//   - ctx context.Context
//   - param user.SignInParam
func (_e *MockIService_Expecter) SignIn(ctx interface{}, param interface{}) *MockIService_SignIn_Call {
	return &MockIService_SignIn_Call{Call: _e.mock.On("SignIn", ctx, param)}
}

func (_c *MockIService_SignIn_Call) Run(run func(ctx context.Context, param user.SignInParam)) *MockIService_SignIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.SignInParam
		if args[1] != nil {
			arg1 = args[1].(user.SignInParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_SignIn_Call) Return(userWithTokenResponse user.UserWithTokenResponse, err error) *MockIService_SignIn_Call {
	_c.Call.Return(userWithTokenResponse, err)
	return _c
}

func (_c *MockIService_SignIn_Call) RunAndReturn(run func(ctx context.Context, param user.SignInParam) (user.UserWithTokenResponse, error)) *MockIService_SignIn_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function for the type MockIService
func (_mock *MockIService) SignUp(ctx context.Context, param user.SignUpParam) (user.UserResponse, error) {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 user.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.SignUpParam) (user.UserResponse, error)); ok {
		return returnFunc(ctx, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.SignUpParam) user.UserResponse); ok {
		r0 = returnFunc(ctx, param)
	} else {
		r0 = ret.Get(0).(user.UserResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.SignUpParam) error); ok {
		r1 = returnFunc(ctx, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockIService_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - param user.SignUpParam
func (_e *MockIService_Expecter) SignUp(ctx interface{}, param interface{}) *MockIService_SignUp_Call {
	return &MockIService_SignUp_Call{Call: _e.mock.On("SignUp", ctx, param)}
}

func (_c *MockIService_SignUp_Call) Run(run func(ctx context.Context, param user.SignUpParam)) *MockIService_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.SignUpParam
		if args[1] != nil {
			arg1 = args[1].(user.SignUpParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_SignUp_Call) Return(userResponse user.UserResponse, err error) *MockIService_SignUp_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockIService_SignUp_Call) RunAndReturn(run func(ctx context.Context, param user.SignUpParam) (user.UserResponse, error)) *MockIService_SignUp_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIStore creates a new instance of MockIStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStore {
	mock := &MockIStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIStore is an autogenerated mock type for the IStore type
type MockIStore struct {
	mock.Mock
}

type MockIStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStore) EXPECT() *MockIStore_Expecter {
	return &MockIStore_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockIStore
func (_mock *MockIStore) CreateUser(ctx context.Context, user1 *user.User) error {
	ret := _mock.Called(ctx, user1)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = returnFunc(ctx, user1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIStore_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockIStore_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user1 *user.User
func (_e *MockIStore_Expecter) CreateUser(ctx interface{}, user1 interface{}) *MockIStore_CreateUser_Call {
	return &MockIStore_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user1)}
}

func (_c *MockIStore_CreateUser_Call) Run(run func(ctx context.Context, user1 *user.User)) *MockIStore_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_CreateUser_Call) Return(err error) *MockIStore_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIStore_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user1 *user.User) error) *MockIStore_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsUserEmailByIgnoreCase provides a mock function for the type MockIStore
func (_mock *MockIStore) ExistsUserEmailByIgnoreCase(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ExistsUserEmailByIgnoreCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIStore_ExistsUserEmailByIgnoreCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsUserEmailByIgnoreCase'
type MockIStore_ExistsUserEmailByIgnoreCase_Call struct {
	*mock.Call
}

// ExistsUserEmailByIgnoreCase is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockIStore_Expecter) ExistsUserEmailByIgnoreCase(ctx interface{}, email interface{}) *MockIStore_ExistsUserEmailByIgnoreCase_Call {
	return &MockIStore_ExistsUserEmailByIgnoreCase_Call{Call: _e.mock.On("ExistsUserEmailByIgnoreCase", ctx, email)}
}

func (_c *MockIStore_ExistsUserEmailByIgnoreCase_Call) Run(run func(ctx context.Context, email string)) *MockIStore_ExistsUserEmailByIgnoreCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_ExistsUserEmailByIgnoreCase_Call) Return(err error) *MockIStore_ExistsUserEmailByIgnoreCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIStore_ExistsUserEmailByIgnoreCase_Call) RunAndReturn(run func(ctx context.Context, email string) error) *MockIStore_ExistsUserEmailByIgnoreCase_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByEmail provides a mock function for the type MockIStore
func (_mock *MockIStore) FindUserByEmail(ctx context.Context, email string) (*user.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStore_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type MockIStore_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockIStore_Expecter) FindUserByEmail(ctx interface{}, email interface{}) *MockIStore_FindUserByEmail_Call {
	return &MockIStore_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", ctx, email)}
}

func (_c *MockIStore_FindUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockIStore_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_FindUserByEmail_Call) Return(user1 *user.User, err error) *MockIStore_FindUserByEmail_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockIStore_FindUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*user.User, error)) *MockIStore_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}
