{
 "title": "coupon-service-logs",
 "description": "Coupon Service Logs V1",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "All Coupon Service Logs",
   "type": "logs",
   "description": "All Coupon Service Logs in JSON",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"coupon-service\"}"
    }
   ]
  },
  {
   "title": "Coupon Issue Failed",
   "type": "timeseries",
   "description": "Detected more than 3 errors when issuing coupons in the last 10 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=\"coupon-service\"} |= \"Failed to issue new coupon\" [10m])"
    }
   ]
  },
  {
   "title": "Coupon Invalid Period",
   "type": "timeseries",
   "description": "Coupons attempted to be issued outside valid policy period detected in last 10 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=\"coupon-service\"} |= \"Coupon policy is not valid in the current period\" [10m])"
    }
   ]
  },
  {
   "title": "Coupon Policy Quota Exceeded",
   "type": "timeseries",
   "description": "Coupons attempted to be issued exceeding the policy quota in the last 10 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({sevice_name=\"coupon-service\"} |= \"Coupon policy quota exceeded\" [10m])"
    }
   ]
  }
 ]
}