services:
  postgres:
    image: postgres:17.6
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: backerhub
      POSTGRES_USER: backeruser
      POSTGRES_PASSWORD: backerpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backerhub_backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backeruser -d backerhub"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:9.8
    container_name: pgadmin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@backerhub.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - backerhub_backend_net
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  backerhub_backend_net:
    driver: bridge
