server:
  port: ${SERVER_PORT:8084}
  shutdown: graceful

spring:
  application:
    name: ${SERVER_NAME:TIMESALE-SERVICE}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/promotions_timesaledb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:my-secret-pw}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: timesale-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
    producer:
      acks: all
      retries: 3
      max-in-flight-requests-per-connection: 1
    concurrency: 3

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka/}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  server:
    port: ${SERVER_METRIC_PORT:7072}
  endpoints:
    web:
      exposure:
        include: health,metrics