app:
  name: user-service
  version: 1.0.0
  host: 0.0.0.0
  port: 8081
  idleTimeout: "30s"

mongo:
  uri: "mongodb://root:secret@localhost:27017"
  dbName: "userdb"

jwt:
  secretKey: "supersecret"
  expiry: "10h"

log:
  level: debug
  output: both          # stdout, file, or both
  filePath: logs/app.log
  prettyConsole: true
