// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/couponPolicies": {
            "get": {
                "description": "Get coupon policies by ID, code, or name. If no parameters are provided, return all coupon policies.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coupon Policy"
                ],
                "summary": "Search coupon policies (by ID, Code, Name, or all)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Coupon Policy ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Coupon Code",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Coupon Name",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/coupon.CouponPolicy"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/couponPolicies/dummy": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coupon Policy"
                ],
                "summary": "Create dummy coupon policies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/coupon.CouponPolicy"
                            }
                        }
                    }
                }
            }
        },
        "/coupons/issue": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Issues a coupon based on the given coupon policy code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coupons"
                ],
                "summary": "Issue a coupon for the current user",
                "parameters": [
                    {
                        "description": "Coupon issue request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/coupon.IssueCouponRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/coupon.Coupon"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/coupons/policy/{policyCode}": {
            "get": {
                "description": "Retrieves all coupons issued for a specific coupon policy code",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coupons"
                ],
                "summary": "Get coupons by policy code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Coupon Policy Code",
                        "name": "policyCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/coupon.Coupon"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/coupons/user": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieves all coupons owned by the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coupons"
                ],
                "summary": "Get all coupons of current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/coupon.Coupon"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/coupons/{code}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieves coupon details by code for the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coupons"
                ],
                "summary": "Get coupon by code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Coupon Code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/coupon.Coupon"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/coupons/{code}/cancel": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Cancels a previously issued coupon",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coupons"
                ],
                "summary": "Cancel a coupon",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Coupon Code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/coupon.Coupon"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/coupons/{code}/use": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Marks the coupon as used for a given order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coupons"
                ],
                "summary": "Use a coupon for an order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Coupon Code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Use coupon request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/coupon.UseCouponRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/coupon.Coupon"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "coupon.Coupon": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "couponPolicy": {
                    "$ref": "#/definitions/coupon.CouponPolicy"
                },
                "couponPolicyId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "orderId": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/coupon.CouponStatus"
                },
                "updatedAt": {
                    "type": "string"
                },
                "usedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "coupon.CouponPolicy": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "coupons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/coupon.Coupon"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "discountType": {
                    "$ref": "#/definitions/coupon.DiscountType"
                },
                "discountValue": {
                    "type": "integer"
                },
                "endTime": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "maximumDiscountAmount": {
                    "type": "integer"
                },
                "minimumOrderAmount": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "totalQuantity": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "coupon.CouponStatus": {
            "type": "string",
            "enum": [
                "AVAILABLE",
                "USED",
                "EXPIRED",
                "CANCELED"
            ],
            "x-enum-varnames": [
                "CouponStatusAvailable",
                "CouponStatusUsed",
                "CouponStatusExpired",
                "CouponStatusCanceled"
            ]
        },
        "coupon.DiscountType": {
            "type": "string",
            "enum": [
                "FIXED_AMOUNT",
                "PERCENTAGE"
            ],
            "x-enum-varnames": [
                "DiscountTypeFixedAmount",
                "DiscountTypePercentage"
            ]
        },
        "coupon.IssueCouponRequest": {
            "type": "object",
            "properties": {
                "couponPolicyCode": {
                    "type": "string"
                }
            }
        },
        "coupon.UseCouponRequest": {
            "type": "object",
            "properties": {
                "orderId": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-USER-ID",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "4.0",
	Host:             "",
	BasePath:         "/api/v4",
	Schemes:          []string{},
	Title:            "Coupon API V4",
	Description:      "Coupon API V4",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register("couponSwaggerV4", SwaggerInfo)
}
