services:
  mongodb:
    container_name: finly-mongodb
    image: mongo:7
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=securepassword123
    ports:
      - 27017:27017
    volumes:
      - ./scripts/mongo/init-db.js:/docker-entrypoint-initdb.d/init-db.js
      - mongo_data:/data/db
    networks:
      - finly-network
    healthcheck:
      test: ["CMD", "mongosh", "--username=admin", "--password=securepassword123", "--authenticationDatabase=admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    container_name: finly-mongo-express
    image: mongo-express:1.0.2
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=securepassword123
      - ME_CONFIG_BASICAUTH=false
    ports:
      - 8081:8081
    networks:
      - finly-network

volumes:
  mongo_data:

networks:
  finly-network:
    driver: bridge