server:
  shutdown: graceful

spring:
  application:
    name: ${SERVER_NAME:POINT-SERVICE-BATCH}
  batch:
    batch:
      job:
        enabled: true # Enables automatic execution of a Spring Batch Job at application startup.
        # When a jobName is provided via command line arguments (jobName=...),
        # Spring Boot will find the matching Job bean and launch it with the given parameters.
        # Disables automatic job execution at startup.
        # Jobs will not run even if jobName and parameters are passed via CLI.
        # Use this when you want to launch jobs manually (e.g., from code, scheduler, or external trigger).
    initialize-schema: always
    thread:
      pool:
        core-size: 4        # The number of core threads to keep in the thread pool, even if they are idle.
        max-size: 10        # The maximum number of threads allowed in the thread pool.
        queue-capacity: 100 # The capacity of the queue to hold tasks before new threads are created.
        # If the queue is full and all threads are busy, new tasks may be rejected.
  datasource:
    batch:
      url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password:
    point:
      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/promotions_pointdb}
      username: ${SPRING_DATASOURCE_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_PASSWORD:my-secret-pw}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

logging:
  level:
    org.springframework.batch: DEBUG
    com.example.point.batch: DEBUG

point-service:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/promotions_pointdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:my-secret-pw}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10