version: '2.8'

services:
  db:
    container_name: open-music-postgres
    image: postgres:15.2
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - pw-bridge
    expose:
      - 5432
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '5'

networks:
  pw-bridge:
    driver: bridge