app:
  name: "order-service"
  port: 8083
  env: "development"

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "my-secret-pw"
  dbname: "order_db"
  sslmode: "disable"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "1h"

logger:
  level: "info"
  filepath: "logs/app.log"