index:
	node index.js

events:
	node events/index.js

filesystem:
	node filesystem/index.js

modulatization:
	node modulatization/index.js

npm:
	node node-package-manager/index.js

process-object:
	node process-object/index.js

stream:
	node stream/inde.js