services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - witrack_net

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: on-failure
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secret123
    ports:
      - "5050:8081"
    networks:
      - witrack_net
    depends_on:
      - mongo

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: on-failure
    environment:
      MONGODB_URI: mongodb://root:secret@mongo:27017/witickets?authSource=admin
      JWT_SECRET: YXV0aGVudGljYXRlVGhpczM2Qnl0ZXNLZXkYXV0aGVudGljYXRlVGhpczM2Qnl0ZXNLZXk
      JWT_EXPIRY_IN: 86400000
      CLIENTS_ALLOWED: http://localhost:8080
    ports:
      - "8081:8081"
    networks:
      - witrack_net
    depends_on:
      - mongo

volumes:
  mongo_data:

networks:
  witrack_net:
    driver: bridge