services:
  gateway:
    container_name: gateway
    image: traefik:v3.4.4
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.file.directory=/rules
    ports:
      - "8080:80"
      - "5052:8080"
    volumes:
      - ./rules:/rules
      - /var/run/docker.sock:/var/run/docker.sock