app:
  name: "account-service"
  port: 8081
  env: "development"

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "my-secret-pw"
  dbname: "account_db"
  sslmode: "disable"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "1h"

jwt:
  secret_key: "S3cr3tK3yS3cr3tK3yS3cr3tK3yS3cr3tK3yS3cr3tK3yS3cr3tK3y"
  expires_in: "24h"

logger:
  level: "info"
  filepath: "logs/account.log"